### ISSUE TITLE
Doesn't pick up correct dune version

### ISSUE THREAD

**Issue by mimoo** [ocurrent/opam-dune-lint#30] opened 2021-05-14 17:09 UTC
I ran into this issue: my opam package file didn't have the right version constraints:

```
  "dune" {>= "2.5"}
```

mirroring what was in my dune file:

```
(lang dune 2.8)
```

cf https://github.com/ocaml/opam-repository/pull/18679#issuecomment-841373486

**Comment by talex5** [comment] 2021-05-17 08:50
Note: if you let dune generate your opam files it will set the constraint automatically: https://dune.readthedocs.io/en/latest/opam.html?highlight=opam#generating-opam-files

**Comment by mimoo** [comment] 2021-05-17 16:41
What are the other advantages of using dune to generate your opam files? I'm thinking that it's annoying because you have to manually generate them before pushing things to your repo. Also if a contributor doesn't see that we're using dune to generate an opam file they'll just update the opam file instead. I guess this can be caught in CI... but it feels awkward to have to have two files with redundant information.

**Comment by talex5** [comment] 2021-08-12 11:07
(closing, as looks like a duplicate of #28)

**Closed as completed by talex5** 2021-08-12 11:07 UTC
