### ISSUE TITLE
error running in the ocaml-tar repository

### ISSUE THREAD

**Issue by hannesm** [ocurrent/opam-dune-lint#65] opened 2024-02-01 17:26 UTC
with ocaml-ci in action, we see:
```
/src: (run (shell "opam exec -- opam-dune-lint"))
opam-dune-lint: internal error, uncaught exception:
                Failure("Sexplib.Sexp.input_rev_sexps: reached EOF while in state Parsing_atom")
                
"/usr/bin/env" "bash" "-c" "opam exec -- opam-dune-lint" failed with exit status 125
```

log file https://ocaml.ci.dev/github/mirage/ocaml-tar/commit/7863fd8b7781d9f58d9301ff770ca18d2fc9b7aa/variant/%28lint-opam%29

**Comment by moyodiallo** [comment] 2024-02-03 14:00
This is issue is fixed on the new `release v0.5`. It was caused by the line https://github.com/ocurrent/opam-dune-lint/blob/30ec26ff1e788847fd5e759ba8fdaf06a05cf924/dune_project.ml#L13 The file is parsed incrementally and at some point we write in the same file.  

Already tested with the new version ( the commit fix was https://github.com/ocurrent/opam-dune-lint/commit/d472b86bdc01e2c3037e8e84886be8e05bd6846d) .

**Closed as completed** 2024-02-05 09:38 UTC

**Comment by hannesm** [comment] 2024-02-06 17:44
Thanks a lot for your fix and deploying that fix live. :)

**Comment by moyodiallo** [comment] 2024-02-06 17:48
> Thanks a lot for your fix and deploying that fix live. :)

👍  Thanks for reporting too.
